### ISSUE TITLE
I am unable to get any of the 5.13 kernels

### ISSUE THREAD

**Issue by abun880007** [peseoane/linux-wsl#10]
I am unable to get any of the 5.13 kernels to run they always error and lock WSL2 up

**Comment by peseoane** [comment]
Hello!

That's because you have to first disable the Linux sub-environment, reboot, then re-enable it and it works again.

This is because they have changed the implementation.

On my "old" Windows 10 they wouldn't load either, I did that, disabled the feature, rebooted, enabled it and 100% functional agian.

**Comment by peseoane** [comment]
Nope, it's a bug... after a minute the VM breaks... but the latest stable works perfectly.

I would go to check what's happening... strange.

**Comment by peseoane** [comment]
Now works!

Issue closed?

![image](https://user-images.githubusercontent.com/47398995/124499946-25f16080-ddbf-11eb-81f1-b385ead80d65.png)

**Comment by peseoane** [comment]
> I am unable to get any of the 5.13 kernels to run they always error and lock WSL2 up

Now works!

Issue closed?

![image](https://user-images.githubusercontent.com/47398995/124499973-343f7c80-ddbf-11eb-8374-8d0c237634c4.png)
