### ISSUE TITLE
5.14 rc1 erroring with wsl2

### ISSUE THREAD

**Issue by abun880007** [peseoane/linux-wsl#11]
5.14 rc1 erroring with wsl2 it just errors and freezes

**Comment by peseoane** [comment]
Hello, **please** if we make a report/problem to be useful **we must provide information**, thanks.

Despite this, is that I do not know ... without providing any data is complicated... 

For my part I can tell you that it has been tested on an Intel system 10 generation and 11, both systems are using the latest version of Windows 10 (21H1 19043.1010) and none has reported me problems. ¿Are you AMD user? What system?... something?..

On the one hand **it's a pre-release**, if you look directly at Kernel.org you'll see a higher than normal number of changes, in fact Microsoft's original instructions for creating a compatible image don't work without a bit of tweaking.

My instance, at least, has been running for over 6 hours so far without a single, 90% load on average without incident.

**What I do when I have problems is, since you have the source code, try a clean configuration from the Microsoft base, which is available here.**

https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-5.10.y/Microsoft

**Comment by peseoane** [comment]
I just restarted the WSL2 enviroment... 35 min ago (when i see your issue) and... for me it's working 😕

<img width="698" alt="Captura" src="https://user-images.githubusercontent.com/47398995/125696331-5ff9121c-877a-4638-b377-dba96f72617c.PNG">

**Comment by abun880007** [comment]
Hi Pedro,

I am running the latest Windows 11 Preview build on a Gen 11 Intel processor and I get the error message below when trying the 5.14 kernel.

![image](https://user-images.githubusercontent.com/1984470/125781538-aade8cd9-c1ad-4287-b021-3f268f4573dc.png)


Kind Regards,

Abun880007

**Comment by peseoane** [comment]
Hi, this seems more a WSL2 issue, but reading, if helps,

I'm reading in another thread... 

https://github.com/yuk7/container-systemd-init-tool/issues/21

Seems when the user upgrades the kernel, you need to patch using the emergency console the console.

```powershell
wsl -d YOUR_DISTRO --exec "/usr/.bin/bash"
export PATH=/usr/.bin:$PATH
vim /boot/init_wsl2/script.sh
```

For some users, same issue SEEMS to be ok with that patch, seems!

(I'm using fish not bash... but not in start-up time, because it freezes).

In any case, it seems to be a deeper failure of Docker and WSL2 integration as far as I can understand.

11th generation processors have problems with GCC, the linker...

On my laptop which is an 11th i can't even compile the kernel, with same image as on the 10th workstation, without any problems.

Try what the other affected users say but if you need docker (this is my guess).

**Comment by abun880007** [comment]
Hi thanks for the information will give those few things a try

Kind Regards,


abun880007

**Comment by peseoane** [comment]
> Hi thanks for the information will give those few things a try Kind Regards, abun880007
> […](#)
> On Thu, 15 Jul 2021, 13:07 Pedro Vicente Seoane Prado, < ***@***.***> wrote: Hi, this seems more a WSL2 issue, but reading, if healps, I'm reading in another thread... [yuk7/container-systemd-init-tool#21](https://github.com/yuk7/container-systemd-init-tool/issues/21) <https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyuk7%2Fcontainer-systemd-init-tool%2Fissues%2F21&data=04%7C01%7C%7C937e3f8efc7448c01e9808d9478918c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619476414577607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CCWV0pf6A8HhHTJ56FqBHO1QJDEfSKyEhDf5cBdeZoQ%3D&reserved=0> Seems when the user upgrades the kernel, you need to patch using the emergency console the console. wsl -d YOUR_DISTRO --exec "/usr/.bin/bash" export PATH=/usr/.bin:$PATH vim /boot/init_wsl2/script.sh For some users, same issue SEEMS to be ok with that patch, seems! (I'm using fish not bash... but not in start-up time, because it freezes). In any case, it seems to be a deeper failure of Docker and WSL2 integration as far as I can understand. 11th generation processors have problems with GCC, the linker... On my laptop which is an 11th i can't even compile the kernel, with same image as on the 10th workstation, without any problems. Try what the other affected users say but if you need docker (this is my guess). — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpeseoane%2Flinux-kernels-wsl2%2Fissues%2F11%23issuecomment-880640727&data=04%7C01%7C%7C937e3f8efc7448c01e9808d9478918c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619476414587602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fWYfQC5obi403dtFZat9Aj47RtMfAFHK9rLTzCKR564%3D&reserved=0>, or unsubscribe <https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAPEPVRNICODET736WLRIT3TX3FPPANCNFSM5AMAFVYA&data=04%7C01%7C%7C937e3f8efc7448c01e9808d9478918c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619476414597599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WuP2vqInA0PVTAbOPAJQCDfzoOC%2BLl0HVhWuOubTkrg%3D&reserved=0> .

Hello.

If you are having problems we could try to make a "pure WSL2 build from their repository", but adding 5.14-rc1 to the content... then we would adapt the configuration.

The generated images are much heavier, and include Microsoft elements, this repository, let's say for licensing, uses a pure Kernel.org version, that's why the images are 10 MiB heavier than the typical 70 MiB of a Microsoft one, but the microsoft ones have better support apparently for bugs like the one you showed me.

Let me know what you think, or we can make a specific NT branch. 😄
